/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcelo
 */
public final class ListarCliente extends javax.swing.JFrame {

    /**
     * Creates new form ListarCliente
     * @throws java.sql.SQLException
     */
    public ListarCliente() throws SQLException {
        initComponents();
        PopularTabelaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanelEditarCliente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNomeCliente = new javax.swing.JTextField();
        jTextEnderecoCliente = new javax.swing.JTextField();
        jTextTelefoneCliente = new javax.swing.JTextField();
        jButtonSalvarClienteEditado = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNovoCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Cliente", "Endereço", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaClientes);

        jLabel1.setText("Clientes");

        jLabel3.setText("Nome do Cliente");

        jLabel4.setText("Endereço");

        jLabel5.setText("Telefone");

        jButtonSalvarClienteEditado.setText("SALVAR");

        javax.swing.GroupLayout jPanelEditarClienteLayout = new javax.swing.GroupLayout(jPanelEditarCliente);
        jPanelEditarCliente.setLayout(jPanelEditarClienteLayout);
        jPanelEditarClienteLayout.setHorizontalGroup(
            jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                .addGroup(jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(75, 75, 75)
                                .addComponent(jTextTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                                .addGroup(jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextEnderecoCliente)
                                    .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                                        .addComponent(jTextNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jButtonSalvarClienteEditado)))
                .addGap(380, 380, 380))
        );
        jPanelEditarClienteLayout.setVerticalGroup(
            jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4))
                    .addGroup(jPanelEditarClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanelEditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButtonSalvarClienteEditado)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jButtonExcluir.setText("EXCLUIR");

        jButtonNovoCliente.setText("NOVO CLIENTE");
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExcluir)
                .addGap(180, 180, 180)
                .addComponent(jButtonNovoCliente)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonNovoCliente))
                .addGap(28, 28, 28)
                .addComponent(jPanelEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed
        CadastrarCliente novo_cliente = new CadastrarCliente();
        novo_cliente.setVisible(true);
        
    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void jTableListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaClientesMouseClicked
        jPanelEditarCliente.setVisible(true);
        
        int row = jTableListaClientes.getSelectedRow();
        
        String nome_cliente = jTableListaClientes.getValueAt(row, 1).toString();
        String endereco_cliente = jTableListaClientes.getValueAt(row, 2).toString();
        String telefone_cliente= jTableListaClientes.getValueAt(row, 3).toString();
        
       jTextNomeCliente.setText(nome_cliente);
       jTextEnderecoCliente.setText(endereco_cliente);
       jTextTelefoneCliente.setText(telefone_cliente);
    }//GEN-LAST:event_jTableListaClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ListarCliente().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ListarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JButton jButtonSalvarClienteEditado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelEditarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaClientes;
    private javax.swing.JTextField jTextEnderecoCliente;
    private javax.swing.JTextField jTextNomeCliente;
    private javax.swing.JTextField jTextTelefoneCliente;
    // End of variables declaration//GEN-END:variables

public void PopularTabelaClientes() throws SQLException{

    DefaultTableModel model = (DefaultTableModel) jTableListaClientes.getModel();
    model.setNumRows(0);
    
    ConexaoBD con = new ConexaoBD();
    java.sql.Statement st = (java.sql.Statement) con.conexao.createStatement();
    
    String sql = "SELECT * FROM cliente";
   
    ResultSet resultado = st.executeQuery(sql);
    
    while(resultado.next()){
        model.addRow(new Object[]{
            resultado.getString("id_cliente"),
            resultado.getString("nome_cliente"),
            resultado.getString("endereco_cliente"),
            resultado.getString("telefone_cliente")
        });
    }

}


}
