/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marcelo
 */
public final class ListarPedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     * @throws java.sql.SQLException
     */
    public ListarPedidos() throws SQLException, ParseException {
        initComponents();
        PopularTabelaPedidos();
        jPanelEditarPedido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVoltarMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarPedido = new javax.swing.JTable();
        jButtonExcluirPedido = new javax.swing.JButton();
        jButtonNovoPedido = new javax.swing.JButton();
        jPanelEditarPedido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNomePedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextDataPedido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescricaoPedido = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextValorPedido = new javax.swing.JTextField();
        jTextStatusPedidos = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonVoltarMenu.setText("Menu");
        jButtonVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarMenuActionPerformed(evt);
            }
        });

        jLabel2.setText("Pedidos");

        jTableListarPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pedido", "Descrição", "Data", "Valor", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarPedido);

        jButtonExcluirPedido.setText("EXCLUIR");

        jButtonNovoPedido.setText("NOVO PEDIDO");
        jButtonNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoPedidoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Pedido");

        jLabel3.setText("Data Pedido");

        jLabel4.setText("Descrição ");

        jTextAreaDescricaoPedido.setColumns(20);
        jTextAreaDescricaoPedido.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescricaoPedido);

        jLabel5.setText("Valor");

        jLabel6.setText("Status");

        jButtonSalvar.setText("SALVAR");

        javax.swing.GroupLayout jPanelEditarPedidoLayout = new javax.swing.GroupLayout(jPanelEditarPedido);
        jPanelEditarPedido.setLayout(jPanelEditarPedidoLayout);
        jPanelEditarPedidoLayout.setHorizontalGroup(
            jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarPedidoLayout.createSequentialGroup()
                .addGroup(jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarPedidoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelEditarPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextNomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54)
                                .addComponent(jTextDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEditarPedidoLayout.createSequentialGroup()
                                .addGroup(jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(52, 52, 52)
                                .addGroup(jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(jPanelEditarPedidoLayout.createSequentialGroup()
                                        .addComponent(jTextValorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(51, 51, 51)
                                        .addComponent(jTextStatusPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(180, 180, 180))))))
                    .addGroup(jPanelEditarPedidoLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jButtonSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEditarPedidoLayout.setVerticalGroup(
            jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarPedidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNomePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelEditarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextValorPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextStatusPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonSalvar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 816, Short.MAX_VALUE)
                .addComponent(jButtonVoltarMenu)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 358, Short.MAX_VALUE)
                .addComponent(jButtonExcluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jButtonNovoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarMenu)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirPedido)
                    .addComponent(jButtonNovoPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jPanelEditarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarMenuActionPerformed
        
    }//GEN-LAST:event_jButtonVoltarMenuActionPerformed


    private void jButtonNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoPedidoActionPerformed
        NovoPedido novoPedido = new NovoPedido();
        novoPedido.setVisible(true);
    }//GEN-LAST:event_jButtonNovoPedidoActionPerformed

    private void jTableListarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarPedidoMouseClicked
        jPanelEditarPedido.setVisible(true);
        
        int row = jTableListarPedido.getSelectedRow();
        String nome = jTableListarPedido.getValueAt(row, 1).toString();
        String descricao = jTableListarPedido.getValueAt(row, 2).toString();
        String data = jTableListarPedido.getValueAt(row, 3).toString();
        String valor = jTableListarPedido.getValueAt(row, 4).toString();
        String status = jTableListarPedido.getValueAt(row, 5).toString();
        
        jTextNomePedido.setText(nome);
        jTextDataPedido.setText(data);
        jTextAreaDescricaoPedido.setText(descricao);
        jTextValorPedido.setText(valor);
        jTextStatusPedidos.setText(status);
        
        ConexaoBD con;
        try {
            con = new ConexaoBD();
            java.sql.Statement st = (java.sql.Statement) con.conexao.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(ListarPedidos.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erro");
        }
        
    }//GEN-LAST:event_jTableListarPedidoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ListarPedidos().setVisible(true);
            } catch (SQLException | ParseException ex) {
                Logger.getLogger(ListarPedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluirPedido;
    private javax.swing.JButton jButtonNovoPedido;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEditarPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListarPedido;
    private javax.swing.JTextArea jTextAreaDescricaoPedido;
    private javax.swing.JTextField jTextDataPedido;
    private javax.swing.JTextField jTextNomePedido;
    private javax.swing.JTextField jTextStatusPedidos;
    private javax.swing.JTextField jTextValorPedido;
    // End of variables declaration//GEN-END:variables

public void PopularTabelaPedidos() throws SQLException, ParseException{

    DefaultTableModel model = (DefaultTableModel) jTableListarPedido.getModel();
    model.setNumRows(0);
    
    ConexaoBD con = new ConexaoBD();
    java.sql.Statement st = (java.sql.Statement) con.conexao.createStatement();
    
    String sql = "SELECT * FROM pedido";
   
    ResultSet resultado = st.executeQuery(sql);
    
    while(resultado.next()){
        
        String data_banco = resultado.getString("data_pedido");
        Date data_conevertida = new SimpleDateFormat("yyyy-MM-dd").parse(data_banco);
        String data_exibir = new SimpleDateFormat("dd-MM-yyyy").format(data_conevertida);
    
        model.addRow(new Object[]{
            resultado.getString("id_pedido"),
            resultado.getString("nome_pedido"),
            resultado.getString("descricao_pedido"),
            data_exibir,
            resultado.getString("valor_pedido"),
            resultado.getString("status_pedido"),
        });
    
    }
    
}

}

