/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marcelo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     * @throws java.sql.SQLException
     */
    public Menu() throws SQLException {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSaldacao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPedido = new javax.swing.JMenu();
        jMenuPedidos = new javax.swing.JMenuItem();
        jMenuNovoPedido = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuListarProjeto = new javax.swing.JMenuItem();
        jMenuNovoProjeto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuVerEstoque = new javax.swing.JMenuItem();
        jMenuCadastrarProduto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuListarCliente = new javax.swing.JMenuItem();
        jMenuCadastrarCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSaldacao.setText("BEM VINDO!");

        jMenuPedido.setText("PEDIDOS");

        jMenuPedidos.setText("Listar Pedidos");
        jMenuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPedidosActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuPedidos);

        jMenuNovoPedido.setText("Novo Pedido");
        jMenuNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoPedidoActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuNovoPedido);

        jMenuBar1.add(jMenuPedido);

        jMenu2.setText("PROJETOS");

        jMenuListarProjeto.setText("Listar Projetos");
        jMenu2.add(jMenuListarProjeto);

        jMenuNovoProjeto.setText("Novo Projeto");
        jMenuNovoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoProjetoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuNovoProjeto);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("ESTOQUE");

        jMenuVerEstoque.setText("Ver Estoque");
        jMenuVerEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerEstoqueActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuVerEstoque);

        jMenuCadastrarProduto.setText("Novo Produto");
        jMenuCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarProdutoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCadastrarProduto);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("CLIENTE");

        jMenuListarCliente.setText("Listar Clientes");
        jMenuListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuListarCliente);

        jMenuCadastrarCliente.setText("Novo Cliente");
        jMenuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCadastrarCliente);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabelSaldacao, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabelSaldacao)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPedidosActionPerformed
        ListarPedidos listaPedidos;
        try {
            listaPedidos = new ListarPedidos();
            listaPedidos.setVisible(true);
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuPedidosActionPerformed

    private void jMenuNovoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoProjetoActionPerformed
        
    }//GEN-LAST:event_jMenuNovoProjetoActionPerformed

    private void jMenuCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarProdutoActionPerformed
        CadastrarProduto cadastrar_produtos = new CadastrarProduto();
        cadastrar_produtos.setVisible(true);
    }//GEN-LAST:event_jMenuCadastrarProdutoActionPerformed

    private void jMenuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarClienteActionPerformed
        CadastrarCliente cadastra_cliente = new CadastrarCliente();
        cadastra_cliente.setVisible(true);
    }//GEN-LAST:event_jMenuCadastrarClienteActionPerformed

    private void jMenuNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoPedidoActionPerformed
        ListarPedidos novoPedido;
        try {
            novoPedido = new ListarPedidos();
            novoPedido.setVisible(true);
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuNovoPedidoActionPerformed

    private void jMenuListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarClienteActionPerformed
        ListarCliente listar_cliente;
        try {
            listar_cliente = new ListarCliente();
            listar_cliente.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuListarClienteActionPerformed

    private void jMenuVerEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerEstoqueActionPerformed
        ListarProdutos listar_produtos;
        try {
            listar_produtos = new ListarProdutos();
            listar_produtos.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuVerEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Menu().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSaldacao;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastrarCliente;
    private javax.swing.JMenuItem jMenuCadastrarProduto;
    private javax.swing.JMenuItem jMenuListarCliente;
    private javax.swing.JMenuItem jMenuListarProjeto;
    private javax.swing.JMenuItem jMenuNovoPedido;
    private javax.swing.JMenuItem jMenuNovoProjeto;
    private javax.swing.JMenu jMenuPedido;
    private javax.swing.JMenuItem jMenuPedidos;
    private javax.swing.JMenuItem jMenuVerEstoque;
    // End of variables declaration//GEN-END:variables
}
